<h1>Cadastrar Produtos</h1>

<form method="post" action="\index\cadastrar">
	<div class="form-group">
		<label>Nome</label>
		<input type="text" name="nome" class="form-control">
	</div>
	<div class="form-group">
		<label>Preço</label>
		<input type="number" name="preco" class="form-control">
	</div>
	<div class="form-group">
		<label>Descrição</label>
		<textarea class="form-control" name="descricao"></textarea>
	</div>
	<div class="form-group">
		<input type="submit" name="" value="Salvar" class="btn btn-success">
	</div>

</form>
