<!DOCTYPE html>
<html>
<head>
	<title>Sistema Estoque</title>
	<?php 
		echo $this->headLink()->prependStylesheet($this->basePath('css/style.css'));
	 ?>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light bg">
		  <a class="navbar-brand" href="<?= $this->url('application',['action'=>'Index']) ?>">Estoque Produtos</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
		      <li class="nav-item active">
		        <a class="nav-link" href="<?= $this->url('application',['action'=>'Index']) ?>">Home<span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="<?= $this->url('application',['action'=>'Cadastrar']) ?>">Cadastro</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="/usuario/logout">Sair</a>
		      </li>
		    </ul>
		  </div>
		</nav>
	</header>

	<main>
	<br>
		<div class="container-fluid">
			<?php 
				$this->flashHelper();
				echo $this->content;
			 ?>
		</div>
	</main>

	<footer class="footer">
		<div class="container">
			2017
		</div>
	</footer>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

</body>

</html>